# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: lignetestmanagementsystem
services:
  mariadb:
    extends:
      file: ./mariadb.yml
      service: mariadb
    profiles:
      - ''
      - prod
